# Generated by Django 4.2.2 on 2023-06-20 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dozent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
                ('beschreibung', models.TextField(verbose_name='Beschreibung')),
            ],
            options={
                'verbose_name': 'Dozent',
                'verbose_name_plural': 'Dozenten',
            },
        ),
        migrations.CreateModel(
            name='Benutzer',
            fields=[
                ('email', models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='E-Mail')),
                ('password', models.CharField(max_length=250, verbose_name='Passwort')),
                ('dozent', models.ManyToManyField(to='userverwaltung.dozent', verbose_name='Dozent')),
            ],
            options={
                'verbose_name': 'Benutzer',
                'verbose_name_plural': 'Benutzer',
            },
        ),
    ]
